safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
rdiscount:
  extensions: [smart]
permalink:   date
paginate: 3

base_url:  http://elusivetruth.net

# extensions
# Delimeter to be used to seperate whole post from its preview
content_delimeter: "<!--END-->"
