safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
rdiscount:
  extensions: [smart]
permalink:   date

base_url:  http://elusivetruth.net
